---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: attendee-service-source
  type: git
  source:
    uri: https://github.com/benwilcock/attendee-service
    branch: master

- name: cf-deploy-attendee-service
  type: cf
  source:
    api: api.run.pivotal.io
    username: {{cf-user}}
    password: {{cf-password}}
    organization: pivotal-emea-cso
    space: bwilcock

- name: 6h
  type: time
  source: {interval: 6h}

- name: slack-alert
  type: slack-notification
  source:
    url: {{webhook}}
    insecure: true

jobs:
- name: test
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
  - get: 6h
    trigger: true
  - task: test
    file: attendee-service-source/ci/tasks/test.yml

- name: deploy
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [test]
  - get: 6h
    trigger: true
    passed: [test]
  - task: package
    file: attendee-service-source/ci/tasks/package.yml
  - put: cf-deploy-attendee-service
    params:
      manifest: attendee-service-source/manifest.yml
      path: package-output/attendee-service.jar

- name: smoke_test
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [deploy]
  - get: 6h
    trigger: true
    passed: [deploy]
  - task: smoke_test
    file: attendee-service-source/ci/tasks/smoke-test.yml
    params:
      ATTENDEE_SERVICE_URL: {{smoke-test-url}}
  - put: slack-alert
    params:
      text: |
        The smoke test for $BUILD_PIPELINE_NAME has passed.